import {prepareEnquiry,lookupShipment} from './api.js';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const menu=$('.menu-toggle'), mobileMenu=$('#mobile-menu');
function closeMenu({returnFocus=false}={}){if(!menu||!mobileMenu)return;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');mobileMenu.hidden=true;if(returnFocus)menu.focus();}
menu?.addEventListener('click',()=>{if(menu.getAttribute('aria-expanded')==='true'){closeMenu();return;}menu.setAttribute('aria-expanded','true');menu.setAttribute('aria-label','Close navigation');mobileMenu.hidden=false;mobileMenu.querySelector('a')?.focus();});
mobileMenu?.addEventListener('click',event=>{if(event.target.closest('a'))closeMenu();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menu?.getAttribute('aria-expanded')==='true')closeMenu({returnFocus:true});});
window.addEventListener('scroll',()=>$('.header')?.classList.toggle('compact',scrollY>40),{passive:true});
const motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('active');if(motion)e.target.classList.add('reveal');observer.unobserve(e.target);}}),{threshold:.2});$$('.timeline-step,.start-paths article').forEach(el=>observer.observe(el));}
$$('[data-gallery]').forEach(b=>b.addEventListener('click',()=>$('.category-gallery').scrollBy({left:Number(b.dataset.gallery)*$('.category').getBoundingClientRect().width,behavior:motion?'smooth':'instant'})));
$('.supplier-quick')?.addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;if(f.reportValidity())location.href='/product-sourcing/?link='+encodeURIComponent(f.elements.supplier.value)+'#request';});
const params=new URLSearchParams(location.search);if(params.has('link')){const el=$('[name="supplierLink"]');if(el)el.value=params.get('link');}if(params.has('category')){const el=$('[name="description"]');if(el)el.value='I am looking for '+params.get('category')+'. ';}if(params.get('supplier')==='1')$('[name="supplierLink"]')?.focus({preventScroll:true});
if(params.has('method')){const el=$('[name="preference"]');if(el){const m=params.get('method');el.value=m==='Air freight'?'Fastest':m==='Sea freight'?'Lowest cost':'Not sure';}}
$$('[data-form-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-form-tab]').forEach(el=>{const active=el===b;el.classList.toggle('selected',active);el.setAttribute('aria-pressed',String(active));});$$('[data-form-panel]').forEach(el=>el.hidden=el.dataset.formPanel!==b.dataset.formTab);}));
const safeFileTypes=['image/jpeg','image/png','image/webp','application/pdf'];
$$('.enquiry-form').forEach((form,index)=>{
 let files=[],prepared=null;const fileInput=$('[type="file"]',form),list=$('.file-list',form),box=$('.form-error',form);
 const showError=msg=>{box.textContent=msg;box.hidden=false;};
 const renderFiles=()=>{list.replaceChildren();files.forEach((f,i)=>{const li=document.createElement('li');const label=document.createElement('span');label.textContent=f.name+' ('+(f.size/1024/1024).toFixed(1)+' MB)';const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label','Remove '+f.name);remove.addEventListener('click',()=>{files.splice(i,1);renderFiles();});li.append(label,remove);list.append(li);});};
 const addFiles=incoming=>{const next=[...files,...incoming];if(next.length>5)return showError('Choose up to 5 files. Remove a file before adding another.');if(next.some(f=>f.size>10*1024*1024))return showError('Each file must be 10 MB or smaller.');if(next.some(f=>!safeFileTypes.includes(f.type)))return showError('Choose JPG, PNG, WebP or PDF files.');files=next;box.hidden=true;renderFiles();};
 fileInput?.addEventListener('change',()=>{addFiles([...fileInput.files]);fileInput.value='';});const drop=$('.upload',form);drop?.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag-over');});drop?.addEventListener('dragleave',()=>drop.classList.remove('drag-over'));drop?.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag-over');addFiles([...e.dataTransfer.files]);});
 const clearField=el=>{el.classList.remove('invalid');el.removeAttribute('aria-invalid');const id=el.getAttribute('aria-describedby');if(id?.startsWith('error-')){$('#'+id)?.remove();el.removeAttribute('aria-describedby');}};
 $$('input,textarea,select',form).forEach(el=>{el.addEventListener('input',()=>clearField(el));el.addEventListener('change',()=>clearField(el));});
 form.addEventListener('submit',async e=>{e.preventDefault();box.hidden=true;$$('.field-error',form).forEach(el=>el.remove());let first=null;const controls=$$('input:not([type="file"]),textarea,select',form);controls.forEach((el,i)=>{clearField(el);if(el.type==='text'||el.type==='email'||el.type==='url')el.value=el.value.trim();el.setCustomValidity('');if(el.type==='url'&&el.value){try{const u=new URL(el.value);if(!['http:','https:'].includes(u.protocol))el.setCustomValidity('Use a link beginning with https:// or http://.');}catch{el.setCustomValidity('Enter a complete product link, beginning with https://.');}}if(!el.checkValidity()){first||=el;el.classList.add('invalid');el.setAttribute('aria-invalid','true');const error=document.createElement('p');error.className='field-error';error.id=`error-${index}-${i}`;error.textContent=el.validity.valueMissing?'Please complete this field.':el.validationMessage;el.setAttribute('aria-describedby',error.id);el.parentElement.append(error);}});if(first){showError('Please check the highlighted fields and try again.');first.focus();return;}
 const submit=$('button[type="submit"]',form);const old=submit.innerHTML;submit.disabled=true;submit.textContent='Preparing your request…';form.setAttribute('aria-busy','true');try{const data=Object.fromEntries(new FormData(form));delete data.attachments;data.requestType=form.dataset.type;prepared=await prepareEnquiry(data,files);form.classList.add('has-success');$('.form-success',form).hidden=false;$('.form-success',form).focus();}catch{showError('The request could not be prepared. Please try again. Your details are still in this page.');box.focus();}finally{submit.disabled=false;submit.innerHTML=old;form.removeAttribute('aria-busy');}});
 $('.download-request',form).addEventListener('click',()=>{if(!prepared)return;const d=prepared.data;const lines=['MZI Shipping enquiry','Prepared locally. Not sent to MZI Shipping.','',...Object.entries(d).filter(([k])=>k!=='attachments').map(([k,v])=>k.replace(/([A-Z])/g,' $1')+': '+v),'','Attachments (share separately):',...d.attachments.map(f=>f.name)];const blob=new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='MZI-'+form.dataset.type+'-request.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 $('.edit-request',form).addEventListener('click',()=>{form.classList.remove('has-success');$('.form-success',form).hidden=true;$('input,textarea,select',form)?.focus();});
});
$('.tracking-form')?.addEventListener('submit',async e=>{e.preventDefault();const el=$('#tracking-number');el.value=el.value.trim();if(!el.reportValidity())return;await lookupShipment(el.value);$('.tracking-result').hidden=false;$('.tracking-result').focus();});

$$('[data-shipping-estimator]').forEach(card=>{
 const products={jumpingCastle:{weight:25,size:[120,55,45]},ledStrip:{weight:.4,size:[25,18,8]},phone:{weight:.25,size:[18,10,5]},tv:{weight:7,size:[120,20,75]},electronicBillboard:{weight:35,size:[120,70,18]},streetLight:{weight:12,size:[130,30,25]},skateboard:{weight:2.8,size:[85,24,14]},doll:{weight:.35,size:[28,15,10]},kitchenAppliance:{weight:3,size:[38,30,30]},storageContainer:{weight:1.1,size:[55,40,35]},tShirt:{weight:.25,size:[30,25,5]},sneakers:{weight:.9,size:[34,22,14]},backpack:{weight:.8,size:[45,32,16]},suitcase:{weight:4,size:[70,48,28]},tablet:{weight:.65,size:[29,20,6]},laptop:{weight:2.1,size:[40,30,8]},speaker:{weight:1.2,size:[28,18,18]},toyCar:{weight:.6,size:[30,18,15]},gamingConsole:{weight:3.5,size:[45,35,15]},powerBank:{weight:.4,size:[20,12,5]}};
 const rates={zimbabwe:[18,25],zambia:[18,25],uk:[10,10],us:[10,10],australia:[10,10]};
 const mode=$('[name="estimateMode"]',card),item=$('[name="estimateItem"]',card),quantity=$('[name="estimateQuantity"]',card),destination=$('[name="estimateDestination"]',card),packing=$('[name="estimatePacking"]',card),length=$('[name="estimateLength"]',card),width=$('[name="estimateWidth"]',card),height=$('[name="estimateHeight"]',card),weight=$('[data-estimate-weight]',card),chargeable=$('[data-estimate-chargeable]',card),rateEl=$('[data-estimate-rate]',card),price=$('[data-estimate-price]',card),cbm=$('[data-estimate-cbm]',card),time=$('[data-estimate-time]',card),timeLabel=$('[data-estimate-time-label]',card),note=$('[data-estimate-note]',card),airResults=$$('[data-air-result]',card),seaResults=$$('[data-sea-result]',card);
 const formatWeight=value=>`${value.toFixed(value<10?1:0)} kg`;
 const update=()=>{
  const product=products[item.value],units=Math.max(1,Number(quantity.value)||1),isProtected=packing.value==='protected',massAllowance=isProtected?.4:.18,volumeAllowance=isProtected?1.18:1.08;
  const entered=[Number(length.value),Number(width.value),Number(height.value)],hasSupplierDimensions=entered.every(value=>value>0),dimensions=hasSupplierDimensions?entered:product.size;
  const packedWeight=(product.weight+massAllowance)*units,volumetricWeight=(dimensions[0]*dimensions[1]*dimensions[2]*volumeAllowance*units)/5000,chargeableWeight=Math.max(packedWeight,volumetricWeight),cargoCbm=(dimensions[0]*dimensions[1]*dimensions[2]*volumeAllowance*units)/1000000,rate=rates[destination.value],isAir=mode.value==='air';
  weight.textContent=formatWeight(packedWeight);chargeable.textContent=formatWeight(chargeableWeight);cbm.textContent=`${cargoCbm.toFixed(cargoCbm<1?2:1)} CBM`;
  rateEl.textContent=rate[0]===rate[1]?`US$${rate[0]} per kg`:`US$${rate[0]} to US$${rate[1]} per kg`;
  price.textContent=rate[0]===rate[1]?`US$${Math.ceil(chargeableWeight*rate[0])}`:`US$${Math.floor(chargeableWeight*rate[0])} to US$${Math.ceil(chargeableWeight*rate[1])}`;
  time.textContent=isAir?'2 to 4 weeks':'50 to 60 days after shipment';timeLabel.textContent=isAir?'Estimated air transit':'Estimated sea transit';
  airResults.forEach(el=>el.hidden=!isAir);seaResults.forEach(el=>el.hidden=isAir);
  note.textContent=`Rough estimate only. ${hasSupplierDimensions?'Supplier':'Typical'} dimensions: ${dimensions.join(' × ')} cm per item. ${isProtected?'Protected packing':'A carton and basic wrapping'} is included. ${isAir?'Air freight is priced per kg using chargeable weight.':'Sea freight is measured in CBM and needs a route-specific quote.'} Battery products, oversized cargo and restricted goods need confirmation before shipping.`;
 };
 [mode,item,quantity,destination,packing,length,width,height].forEach(field=>{field.addEventListener('input',update);field.addEventListener('change',update);});
 update();
});
