import {button,eyebrow,arrow,pageHero,gallery,timeline,shippingMethods,freightGuide,shippingCalculator,trust,faq,cta} from './components.mjs';
import {form} from './forms.mjs';
import {steps,categories} from './content.mjs';
export const paths=()=>`<section class="section wrap start-section" id="your-next-move"><div class="section-heading"><div>${eyebrow('YOUR NEXT MOVE')}<h2>Start with where you are.</h2></div><p>Still looking, already found it, or ready to ship?<br>There is a place to start.</p></div><div class="start-paths"><article><span class="path-icon" aria-hidden="true">⌕</span><h3>Find it for me.</h3><p>Tell us what you need. We help identify sourcing options in China.</p><a class="text-link" href="/product-sourcing/#request">Start a sourcing request ${arrow}</a></article><article class="supplier-path"><span class="path-icon" aria-hidden="true">↗</span><h3>I already found it.</h3><p>Have a product or supplier link? Send it over with your quantity.</p><form class="supplier-quick"><label class="sr-only" for="quick-link">Product or supplier URL</label><input id="quick-link" type="url" name="supplier" placeholder="Paste Alibaba, 1688 or supplier link" required><button aria-label="Continue with supplier link" type="submit">↗</button></form></article><article><span class="path-icon" aria-hidden="true">⇢</span><h3>I only need shipping.</h3><p>Your goods are ready. Let’s work out how to get them to you.</p><a class="text-link" href="/shipping/#request">Get a shipping quote ${arrow}</a></article></div></section>`;
function home(){return `<section class="cinema-hero" aria-label="Sourcing and shipping from China"><div class="cinema-media" data-vault="hero-18"><video class="hero-video" autoplay muted loop playsinline preload="metadata" poster="/assets/hero-container-port.webp" aria-hidden="true"><source media="(max-width: 640px)" src="/assets/hero-container-port-mobile.mp4" type="video/mp4"><source src="/assets/hero-container-port.mp4" type="video/mp4"></video><img src="/assets/hero-container-port.webp" width="1600" height="900" alt="Container ship loading at a terminal" fetchpriority="high"></div><div class="cinema-content"><div class="hero-kicker"><span><i></i> YOUR CONNECTION TO CHINA</span><span>SOURCING / INSPECTION / FREIGHT</span></div><div class="cinema-title"><h1><span>From China.</span><span>To <em>what’s next.</em></span></h1><p>The machine that starts your business. The furniture that makes it home. We help you source it, check it and ship it.</p><div class="buttons">${button('Find a product','/product-sourcing/#request')}${button('Estimate shipping','/shipping/#estimate',true)}</div><a href="/product-sourcing/?supplier=1#request" class="text-link">Already have a supplier? Start here ${arrow}</a></div><div class="hero-bottom"><div class="route-signature"><span>CN</span><div><small>ON THE GROUND IN CHINA</small><strong>Connected to your destination</strong></div></div><a href="#your-next-move" class="explore-link">EXPLORE YOUR OPTIONS <span aria-hidden="true">↓</span></a></div></div></section><div class="capability-strip wrap"><span>ONE TEAM. FROM SOURCE TO SHIPMENT.</span><p>Sourcing <i>↗</i> Inspection <i>↗</i> Consolidation <i>↗</i> Air & sea freight</p></div>${paths()}${gallery()}${timeline()}${shippingMethods()}${trust()}${form('sourcing',true)}${faq(5)}${cta()}`;}
const serviceDetails=(title,items)=>`<section class="section wrap"><div class="section-heading"><h2>${title}</h2></div><div class="service-details">${items.map(([h,p])=>`<article><h3>${h}</h3><p>${p}</p></article>`).join('')}</div></section>`;
const legal=(title,sections)=>`<section class="legal wrap">${eyebrow('MZI SHIPPING')}<h1>${title}</h1><p class="legal-date">Last updated: 13 September 2026</p>${sections.map(([h,p])=>`<section><h2>${h}</h2><p>${p}</p></section>`).join('')}</section>`;
export const pages={
 '/':{title:'China product sourcing & international shipping',description:'MZI Shipping helps you source, inspect, consolidate and ship products from China. Start with a product link, sourcing request or shipping enquiry.',render:home},
 '/product-sourcing/':{title:'Source products from China',description:'Find products and coordinate suppliers in China with MZI Shipping. Share a photo, specifications or an Alibaba, 1688 or supplier link.',render:()=>pageHero('Your next order.<br>Starts in China.','Tell us what you need, or send the product you have already found. We help connect sourcing, supplier coordination and shipping.','furniture.webp','PRODUCT SOURCING')+paths()+serviceDetails('A product link is<br>just the beginning.',[['Find a suitable supplier','Share your requirements so sourcing options can be reviewed against the product, quantity and intended use.'],['Confirm the details','Check specifications, variations, packing and the services you need before proceeding.'],['Prepare for shipment','Coordinate agreed inspection, collection and consolidation requirements alongside freight.']])+gallery()+form()+faq(3)+cta()},
 '/shipping/':{title:'Shipping from China | Air, sea & consolidation',description:'Request a China shipping quote for air freight, sea freight, consolidated cargo or a full container. Share your cargo and destination details.',render:()=>pageHero('Your goods are ready.<br>Let’s get them moving.','A carton, commercial equipment or a full container. Tell us what you are shipping, where it is in China and where it needs to go.','hero.webp','SHIPPING FROM CHINA','Estimate shipping','#estimate')+freightGuide()+shippingCalculator()+shippingMethods()+form('shipping')+faq(8)+cta()},
 '/vehicle-imports/':{title:'Import a vehicle from China',description:'MZI Shipping helps review vehicle sourcing, dealer coordination, inspection and export shipping enquiries from China.',render:()=>pageHero('Found the car?<br>We’ll help with the<br>China side.','Vehicle sourcing, dealer coordination, inspection and shipment preparation. Start with the make, model and destination.','vehicle.webp','VEHICLE IMPORTS')+serviceDetails('Know the vehicle.<br>Understand the next step.',[['Sourcing & dealer coordination','Share the vehicle you want or a dealer link. Confirm the model, specification, condition and purchase status.'],['Inspection','Agree the scope of vehicle checks before inspection. Available records and condition details help inform the next step.'],['Export preparation','The vehicle and route need a review of the relevant documents and handling requirements.'],['Shipping & updates','Review suitable shipping options and agree how updates will reach you. Eligibility and destination requirements vary.']])+`<div class="wrap note-line">Confirm vehicle eligibility and destination requirements before purchase. An enquiry does not guarantee export approval or customs clearance.</div>`+form('vehicle')+cta()},
 '/machinery/':{title:'Source & ship machinery from China',description:'Source and ship industrial, agricultural and commercial machinery from China. Share capacity, electrical specifications and cargo details.',render:()=>pageHero('The machine matters.<br>So do the specifications<br>behind it.','Source and ship machinery with the application, electrical requirements and handling details in view from the start.','machinery.webp','MACHINERY SOURCING & SHIPPING')+serviceDetails('Get the details right<br>before it moves.',[['Application & output','Tell us what the machine will do, the materials it will handle and the capacity you need.'],['Electrical requirements','Share voltage, frequency and phase requirements. A similar-looking model may have different specifications.'],['Dimensions & handling','Packed dimensions, weight and lifting requirements affect collection, loading and freight options.'],['Inspection & documentation','Send specification sheets and available supplier documents. Agree the checks needed before shipment.']])+form('machinery')+cta()},
 '/how-it-works/':{title:'How China sourcing & shipping works',description:'Follow the MZI Shipping process from product enquiry and quotation to inspection, export preparation and shipment updates.',render:()=>pageHero('One process from China<br>to your destination.','Understand what happens before you buy, while your order is prepared and when your shipment moves.',null,'HOW IT WORKS')+timeline()+`<section class="section wrap" id="request">${eyebrow('BEFORE YOU START')}<h2>A few details make<br>a better enquiry.</h2><div class="service-details">${[['Your product','Description, photos, product links and specifications.'],['Your order','Quantity, purchase status and supplier location.'],['Your destination','Country, city and preferred shipping approach.']].map(([h,p])=>`<article><h3>${h}</h3><p>${p}</p></article>`).join('')}</div></section>`+paths()+cta()},
 '/about/':{title:'About MZI Shipping | Based in China',description:'MZI Shipping is based in China and helps individuals and businesses source, coordinate and ship products internationally.',render:()=>pageHero('On the ground in China.<br>On your side of the order.','MZI Shipping helps individuals and businesses source, purchase, inspect, consolidate and ship products from China internationally.','hero.webp','ABOUT MZI SHIPPING')+`<section class="section wrap about-copy" id="request"><h2>Keep the product and<br>the shipment connected.</h2><div><p>Buying from China can mean dealing with different suppliers, product specifications and packing requirements before freight is even discussed.</p><p>We bring those conversations together. Whether you need help finding a supplier, coordinating an existing purchase or shipping goods that are ready, we start with your order.</p><p>Our base is in China. Your product and destination determine the services, documents and shipping options to review.</p>${button('Tell us about your order','/request-a-quote/')}</div></section>`+trust()+cta()},
 '/request-a-quote/':{title:'Request a sourcing or shipping quote',description:'Choose a sourcing, shipping, vehicle or machinery enquiry. Prepare the details MZI Shipping needs to review your request.',render:()=>pageHero('What can we help<br>you bring from China?','Choose your starting point. The form will ask for the details that matter for your order.',null,'REQUEST A QUOTE')+`<section class="wrap quote-picker" id="request" aria-label="Request type">${[['sourcing','Find a product'],['shipping','Shipping only'],['vehicle','Import a vehicle'],['machinery','Source machinery']].map(([v,t],i)=>`<button class="quote-tab ${i===0?'selected':''}" data-form-tab="${v}" aria-pressed="${i===0}">${t}${arrow}</button>`).join('')}</section><div class="quote-panels">${['sourcing','shipping','vehicle','machinery'].map((t,i)=>`<div data-form-panel="${t}" ${i?'hidden':''}>${form(t).replace('id="request"',`id="request-${t}"`)}</div>`).join('')}</div>`},
 '/contact/':{title:'Contact MZI Shipping',description:'Prepare a sourcing, shipping or order enquiry for MZI Shipping, based in China.',render:()=>pageHero('Let’s talk about<br>your order.','A product link, a cargo question or a sourcing brief. Start with what you know and we can work through the details.',null,'CONTACT · BASED IN CHINA')+`<section class="wrap contact-strip"><strong>MZI Shipping · China</strong><p>Direct email, phone and WhatsApp details will be added when confirmed. Existing customers should use the contact channel supplied with their order.</p></section>`+form('contact')+cta()},
 '/track-shipment/':{title:'Track your shipment',description:'Shipment tracking interface for MZI Shipping. Online tracking is not yet connected; contact the team through your agreed order channel.',render:()=>`<section class="tracking-page wrap">${eyebrow('SHIPMENT SUPPORT')}<h1>Follow your<br>shipment.</h1><p>Enter your shipment or order number.</p><form class="tracking-form"><label class="sr-only" for="tracking-number">Shipment or order number</label><input id="tracking-number" name="tracking" placeholder="Shipment or order number" required maxlength="100"><button class="button">Track <span aria-hidden="true">→</span></button></form><p class="fine-print">Online tracking is not connected yet.</p><div class="tracking-result" role="status" tabindex="-1" hidden><h2>Online tracking is not available yet.</h2><p>No live lookup was performed. For an update, share your order number with MZI Shipping through the contact channel provided with your order.</p><a class="text-link" href="/contact/">Contact information ${arrow}</a></div><div class="tracking-journey" aria-hidden="true"><span>Order confirmed</span><i></i><span>Prepared in China</span><i></i><span>In transit</span></div></section>`},
 '/faq/':{title:'Frequently asked questions',description:'Answers about China sourcing, supplier links, machinery, vehicle shipping, consolidation, inspections and shipping quotes.',render:()=>`<section class="page-hero wrap">${eyebrow('BEFORE YOU SHIP')}<h1>A little clarity<br>goes a long way.</h1><p class="lead">Useful answers to the questions that come up before an order.</p></section>`+faq()+cta()},
 '/privacy-policy/':{title:'Privacy policy',description:'How MZI Shipping handles website enquiries and optional messaging consent.',render:()=>legal('Privacy policy',[
 ['Information you provide','The website lets you prepare a local enquiry summary with contact, product and shipping details. It does not currently send the form or upload selected files. Your browser may offer autofill or form restoration.'],
 ['Mobile numbers and messages','MZI Shipping does not sell or share mobile numbers with third parties or affiliates for their marketing or promotional use. If you opt in, MZI Shipping may send shipment updates or up to four marketing text messages a month. Message and data rates may apply.'],
 ['Your choices','SMS consent is optional and is not required to request a quote or service. You can opt out of messages by replying STOP. Reply HELP for support with the messaging service.'],
 ['Files and downloads','Selected photos and documents stay on your device. A downloaded request summary contains file names, not file contents. You choose where to store or share that download.'],
 ['Hosting','The website host may process technical information needed to deliver the site, including network and access information. This website does not use marketing analytics.'],
 ['Questions','Use the MZI Shipping contact channel supplied with your order. Direct contact details will be added to the contact page when confirmed.']])},
 '/terms/':{title:'Website terms',description:'Terms for using the MZI Shipping website, estimates and optional SMS updates.',render:()=>legal('Website terms',[
 ['Using this website','This website introduces MZI Shipping and lets visitors prepare sourcing and shipping enquiries. Completing a form does not place an order, create a shipment, take payment or guarantee a service.'],
 ['Estimates and freight timing','The calculator and freight guide are for planning only. Product type, weight, dimensions, batteries, packing, route availability and clearance requirements can change the price and timeline. Confirm the written quotation before making a purchase.'],
 ['Service enquiries','Supplier coordination, inspection, shipment acceptance and destination requirements need individual review. A request is not a confirmed quotation or service agreement.'],
 ['Optional SMS messages','You may choose separate consent for shipment updates and marketing text messages. Marketing messages are limited to four a month. Consent is not a condition of service. Reply STOP to opt out or HELP for support. Message and data rates may apply.'],
 ['Product information','Provide accurate product, supplier, quantity and packing details. Batteries, regulated goods, vehicles and machinery may require more information and may not be accepted for every route.'],
 ['Business terms','Final commercial terms, company registration details and dispute arrangements are confirmed separately before a customer enters a service agreement.']])},
 '/cookie-policy/':{title:'Cookie notice',description:'Cookies and browser storage used by this MZI Shipping website preview.',render:()=>legal('Cookie notice',[
 ['This website','The website code does not set marketing or analytics cookies. It does not use local storage to save enquiry details or tracking numbers.'],
 ['Hosting and sign-in','Sites may use cookies or similar technology to deliver the website and manage access. Those functions are provided by the hosting service.'],
 ['Your browser','You can review and manage cookies through your browser settings. Browser autofill, saved downloads and form restoration are controlled by your browser and device.'],
 ['Future changes','This notice should be updated before adding analytics, advertising or other services that introduce cookies or browser storage.']])}
};
